Adding staging and production environments to pipeline

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -7,6 +7,31 @@ pr:
 variables:
   imageName: 'jasonhindulak/go-rest-api-example'
 
+  ##################### - QA - #####################
+  qa_url: 'go-api-qa.platform.hyland.io'
+  qa_listen_port: 8080
+  qa_database_username: postgres
+  qa_database_name: postgres
+  qa_database_address: go-api-qa.cprcybwaayux.us-east-1.rds.amazonaws.com
+  qa_token_password: thisdoesntmatter
+  
+  ##################### - Staging - #####################
+  staging_url: 'go-api-staging.platform.hyland.io'
+  staging_listen_port: 8080
+  staging_database_username: postgres
+  staging_database_name: postgres
+  staging_database_address: go-api-staging.cprcybwaayux.us-east-1.rds.amazonaws.com
+  staging_token_password: thisdoesntmatter
+
+  ##################### - Production - #####################
+  prod_url: 'go-api-prod.platform.hyland.io'
+  prod_listen_port: 8080
+  prod_database_username: postgres
+  prod_database_name: postgres
+  prod_database_address: go-api-prod.cprcybwaayux.us-east-1.rds.amazonaws.com
+  prod_token_password: thisdoesntmatter
+
+# For running integrations tests
 resources:
   containers:
     - container: postgres
@@ -21,12 +46,16 @@ stages:
 - stage: CI
   displayName: CI
   jobs:
+
+    ################################################################################
     - job: CI
+    ################################################################################
       services:
         postgres: postgres
       pool:
         vmImage: 'Ubuntu 16.04'
       steps:
+      
         - script: |
             go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
             ~/go/bin/golangci-lint run ./...
@@ -92,21 +121,19 @@ stages:
   displayName:  Deploy to QA
   dependsOn: CI
   jobs:
+
+    ################################################################################
   - deployment: Deploy_QA
+    ################################################################################
     displayName: Deploy to QA
     pool:
       vmImage: 'Ubuntu 16.04'
     environment: 'pe-dev-qa'
-    variables:
-      qa_listen_port: 8080
-      qa_database_username: postgres
-      qa_database_name: postgres
-      qa_database_address: postgres.cprcybwaayux.us-east-1.rds.amazonaws.com
-      qa_token_password: thisdoesntmatter
     strategy:
       runOnce:
         deploy:
           steps:
+          
           - task: HelmInstaller@1
             displayName: Helm installer
             inputs:
@@ -131,4 +158,111 @@ stages:
               chartType: 'FilePath'
               chartPath: '$(HELM_CHART_PACKAGE)'
               releaseName: 'go-api-qa'
-              overrideValues: 'image.tag=$(build.buildId),config.token_password=$(qa_token_password),config.listen_port=$(qa_listen_port),config.MASTER_USERNAME=$(qa_database_username),config.MASTER_PASSWORD=$(qa_database_password),config.DB_NAME=$(qa_database_name),config.ENDPOINT_ADDRESS=$(qa_database_address)'
+              overrideValues: 'image.tag=$(build.buildId),
+                               ingress.hosts[0].host=$(qa_url),
+                               config.token_password=$(qa_token_password),
+                               config.listen_port=$(qa_listen_port),
+                               config.MASTER_USERNAME=$(qa_database_username),
+                               config.MASTER_PASSWORD=$(qa_database_password),
+                               config.DB_NAME=$(qa_database_name),
+                               config.ENDPOINT_ADDRESS=$(qa_database_address)'
+              
+- stage: Deploy_Staging
+  displayName:  Deploy to Staging
+  dependsOn: Deploy_QA
+  jobs:
+
+  ################################################################################
+  - deployment: Deploy_Staging
+  ################################################################################
+    displayName: Deploy to Staging
+    pool:
+      vmImage: 'Ubuntu 16.04'
+    environment: 'pe-dev-staging'
+    strategy:
+      runOnce:
+        deploy:
+          steps:
+          
+          - task: HelmInstaller@1
+            displayName: Helm installer
+            inputs:
+              helmVersionToInstall: 2.14.3
+
+          - script: |
+              set -euo pipefail
+
+              if [[ ! -e $(find $AGENT_BUILDDIRECTORY/helm-chart/go-rest-api-*.tgz) ]]; then
+                  echo "Could not find Helm chart artifact at directory: $AGENT_BUILDDIRECTORY/helm-chart/"
+                  exit 1
+              fi
+              echo "##vso[task.setvariable variable=HELM_CHART_PACKAGE]$(find $AGENT_BUILDDIRECTORY/helm-chart/go-rest-api-*.tgz)"
+            displayName: Get full path to Helm Chart artifact
+
+          - task: HelmDeploy@0
+            inputs:
+              connectionType: 'Kubernetes Service Connection'
+              kubernetesServiceConnection: 'pe-dev.go-api-staging'
+              namespace: 'go-api-staging'
+              command: 'upgrade'
+              chartType: 'FilePath'
+              chartPath: '$(HELM_CHART_PACKAGE)'
+              releaseName: 'go-api-staging'
+              overrideValues: 'image.tag=$(build.buildId),
+                               ingress.hosts[0].host=$(staging_url),
+                               config.token_password=$(staging_token_password),
+                               config.listen_port=$(staging_listen_port),
+                               config.MASTER_USERNAME=$(staging_database_username),
+                               config.MASTER_PASSWORD=$(staging_database_password),
+                               config.DB_NAME=$(staging_database_name),
+                               config.ENDPOINT_ADDRESS=$(staging_database_address)'
+
+- stage: Deploy_Prod
+  displayName:  Deploy to Production
+  dependsOn: Deploy_Staging
+  jobs:
+
+  ################################################################################
+  - deployment: Deploy_Prod
+  ################################################################################
+    displayName: Deploy to Production
+    pool:
+      vmImage: 'Ubuntu 16.04'
+    environment: 'pe-dev-production'
+    strategy:
+      runOnce:
+        deploy:
+          steps:
+          
+          - task: HelmInstaller@1
+            displayName: Helm installer
+            inputs:
+              helmVersionToInstall: 2.14.3
+
+          - script: |
+              set -euo pipefail
+
+              if [[ ! -e $(find $AGENT_BUILDDIRECTORY/helm-chart/go-rest-api-*.tgz) ]]; then
+                  echo "Could not find Helm chart artifact at directory: $AGENT_BUILDDIRECTORY/helm-chart/"
+                  exit 1
+              fi
+              echo "##vso[task.setvariable variable=HELM_CHART_PACKAGE]$(find $AGENT_BUILDDIRECTORY/helm-chart/go-rest-api-*.tgz)"
+            displayName: Get full path to Helm Chart artifact
+
+          - task: HelmDeploy@0
+            inputs:
+              connectionType: 'Kubernetes Service Connection'
+              kubernetesServiceConnection: 'pe-dev.go-api-prod'
+              namespace: 'go-api-prod'
+              command: 'upgrade'
+              chartType: 'FilePath'
+              chartPath: '$(HELM_CHART_PACKAGE)'
+              releaseName: 'go-api-prod'
+              overrideValues: 'image.tag=$(build.buildId),
+                               ingress.hosts[0].host=$(prod_url),
+                               config.token_password=$(prod_token_password),
+                               config.listen_port=$(prod_listen_port),
+                               config.MASTER_USERNAME=$(prod_database_username),
+                               config.MASTER_PASSWORD=$(prod_database_password),
+                               config.DB_NAME=$(prod_database_name),
+                               config.ENDPOINT_ADDRESS=$(prod_database_address)'
